export const FactureService = {
    getFacturesData() {
        return [
            {
                id: '1000',
                code: 'f230fh0g3',
                name: 'Ibrahim Diallo',
                description: 'Facture Description',
                image: 'bamboo-watch.jpg',
                price: 6547854,
                category: 'Accessories',
                quantity: 24,
                factureStatus: 'FINIE',
                rating: 5,
                email: 'ibrahim@yahoo.fr',
                phone: '+224 66 54 85 62',
                address: 'Dogomet-Centre',
                test: {
                    pays: 'test1',
                 }, 
            },
            { 
                id: '1000',
                code: 'f230fh0g3',
                name: 'Maladho BALDE',
                description: 'Facture Description',
                image: 'bamboo-watch.jpg',
                price: 6547854,
                category: 'Accessories',
                quantity: 24,
                factureStatus: 'ARCHIVE',
                rating: 5,
                email: 'ibrahim@yahoo.fr',
                phone: '+224 66 54 85 62',
                address: 'Dogomet-Centre',
                test: {
                    pays: 'RomeoL',
                 }, 
            },
            {
                id: '1001',
                code: 'nvklal433',
                name: 'Moussa Diallo',
                description: 'Facture Description',
                image: 'black-watch.jpg',
                price: 727587496,
                category: 'Accessories',
                quantity: 61,
                factureStatus: 'Partiel',
                rating: 4,
                email: 'moussa@yahoo.fr',
                phone: '+224 622 34 56 78',
                address: 'Dabola Hamdallaye'
            },
            {
                id: '1002',
                code: 'zz21cz3c1',
                name: 'Almamy Barry',
                description: 'Facture Description',
                image: 'blue-band.jpg',
                price: 795478,
                category: 'Fitness',
                quantity: 2,
                factureStatus: 'Brouillon',
                rating: 3,
                email: 'mariam@gmail.com',
                phone: '+33 06 12 34 56 78',
                address: 'Paris 7e'
            },
            {
                id: '1003',
                code: '244wgerg2',
                name: 'Néné Asma',
                description: 'Facture Description',
                image: 'blue-t-shirt.jpg',
                price: 202100,
                category: 'Clothing',
                quantity: 25,
                factureStatus: 'Payé',
                rating: 5,
                email: 'alpha@outlook.fr',
                phone: '+224 620 23 45 67',
                address: 'Conakry Cosa'
            },
            {
                id: '1004',
                code: 'h456wer53',
                name: 'Oumou Sow',
                description: 'Facture Description',
                image: 'adourahmane baldé.jpg',
                price: 1565877,
                category: 'Accessories',
                quantity: 73,
                factureStatus: 'Partiel',
                rating: 4,
                email: 'julie@hotmail.com',
                phone: '+33 07 98 76 54 32',
                address: 'Lyon Croix-Rousse'
            },
            {
                id: '1005',
                code: 'av2231fwg',
                name: 'Adourahmane Baldé',
                description: 'Facture Description',
                image: 'brown-purse.jpg',
                price: 120745874,
                category: 'Accessories',
                quantity: 0,
                factureStatus: 'Partiel',
                rating: 4,
                email: 'abdoulaye@yahoo.fr',
                phone: '+224 622 34 56 78',
                address: 'Dabola Marché'
            },
            {
                id: '1006',
                code: 'bib36pfvm',
                name: 'Moussa Sidibé',
                description: 'Facture Description',
                image: 'chakra-adourahmane baldé.jpg',
                price: 32,
                category: 'Accessories',
                quantity: 5,
                factureStatus: 'Brouillon',
                rating: 3,
                email: 'camille@gmail.com',
                phone: '+33 01 23 45 67 89',
                address: 'Marseille Vieux-Port'
            },
            {
                id: '1007',
                code: 'mbvjkgip5',
                name: 'Elhadj Tall',
                description: 'Facture Description',
                image: 'galaxy-earrings.jpg',
                price: 34,
                category: 'Accessories',
                quantity: 23,
                factureStatus: 'Payé',
                rating: 5,
                email: 'fatoumata@outlook.fr',
                phone: '+224 625 12 34 56',
                address: 'Siguiri Hamdallaye'
            },
            {
                id: '1008',
                code: 'vbb124btr',
                name: 'Mody Ousmane Sy',
                description: 'Facture Description',
                image: 'game-controller.jpg',
                price: 99,
                category: 'Electronics',
                quantity: 2,
                factureStatus: 'Brouillon',
                rating: 4,
                email: 'laurent@hotmail.com',
                phone: '+33 02 98 76 54 32',
                address: 'Bordeaux Saint-Pierre'
            },
            {
                id: '1009',
                code: 'cm230f032',
                name: 'Ali Camara',
                description: 'Facture Description',
                image: 'gaming-set.jpg',
                price: 299,
                category: 'Electronics',
                quantity: 63,
                factureStatus: 'Payé',
                rating: 3,
                email: 'mohamed@yahoo.fr',
                phone: '+224 666 45 67 89',
                address: 'Conakry Cosa'
            },
            {
                id: '1010',
                code: 'plb34234v',
                name: 'Moise Kamano',
                description: 'Facture Description',
                image: 'gold-phone-case.jpg',
                price: 24,
                category: 'Accessories',
                quantity: 0,
                factureStatus: 'Partiel',
                rating: 4,
                email: 'sophie@gmail.com',
                phone: '+33 06 78 12 34 56',
                address: 'Nice Promenade'
            },
            {
                id: '1011',
                code: '4920nnc2d',
                name: 'Green Earbuds',
                description: 'Facture Description',
                image: 'green-earbuds.jpg',
                price: 89,
                category: 'Electronics',
                quantity: 23,
                factureStatus: 'Payé',
                rating: 4,
                email: 'kadiatou@outlook.fr',
                phone: '+224 624 23 45 67',
                address: 'Mamou Abattoir'
            },
            {
                id: '1012',
                code: '250vm23cc',
                name: 'Green T-Shirt',
                description: 'Facture Description',
                image: 'green-t-shirt.jpg',
                price: 49,
                category: 'Clothing',
                quantity: 74,
                factureStatus: 'Payé',
                rating: 5,
                email: 'pierre@hotmail.com',
                phone: '+33 07 65 43 21 09',
                address: 'Montpellier Centre'
            },
            {
                id: '1013',
                code: 'fldsmn31b',
                name: 'Grey T-Shirt',
                description: 'Facture Description',
                image: 'grey-t-shirt.jpg',
                price: 48,
                category: 'Clothing',
                quantity: 0,
                factureStatus: 'Partiel',
                rating: 3,
                email: 'binta@yahoo.fr',
                phone: '+224 620 98 76 54',
                address: 'Conakry Kipé'
            },
            {
                id: '1014',
                code: 'waas1x2as',
                name: 'Headphones',
                description: 'Facture Description',
                image: 'headphones.jpg',
                price: 175,
                category: 'Electronics',
                quantity: 8,
                factureStatus: 'Brouillon',
                rating: 5,
                email: 'nathalie@gmail.com',
                phone: '+33 01 98 76 54 32',
                address: 'Lille Fives'
            },
            {
                id: '1015',
                code: 'vb34btbg5',
                name: 'Light Green T-Shirt',
                description: 'Facture Description',
                image: 'light-green-t-shirt.jpg',
                price: 49,
                category: 'Clothing',
                quantity: 34,
                factureStatus: 'Payé',
                rating: 4,
                email: 'mamadou@outlook.fr',
                phone: '+224 622 54 32 10',
                address: 'Conakry Cité Enco 5'
            },
            {
                id: '1016',
                code: 'k8l6j58jl',
                name: 'Moussa SIDIBE',
                description: 'Facture Description',
                image: 'lime-band.jpg',
                price: 79,
                category: 'Fitness',
                quantity: 12,
                factureStatus: 'Payé',
                rating: 3,
                email: 'jean@hotmail.com',
                phone: '+33 02 34 56 78 90',
                address: 'Toulouse Capitole'
            },
        ];
    },

    getFacturesWithOrdersData() {
        return [
            {
                id: '1000',
                code: 'f230fh0g3',
                name: 'Sy Aissatou',
                description: 'Facture Description',
                image: 'bamboo-watch.jpg',
                price: 65,
                category: 'Accessories',
                phone: '+33 02 34 56 78 90',
                quantity: 24,
                factureStatus: 'Partiel',
                rating: 5,
                orders: [
                    {
                        id: '1000-0',
                        factureCode: 'f230fh0g3',
                        date: '2020-09-13',
                        amount: 5,
                        quantity: 1,
                        customer: 'David James',
                        status: 'PENDING',
                        typePaiement: 'orange',
                    },
                    {
                        id: '1000-1',
                        factureCode: 'f230fh0g3',
                        date: '2020-05-14',
                        amount: 130,
                        quantity: 2,
                        customer: 'Leon Rodrigues',
                        status: 'DELIVERED',
                        typePaiement: 'Espèce',
                    },
                    {
                        id: '1000-2',
                        factureCode: 'f230fh0g3',
                        date: '2019-01-04',
                        amount: 65,
                        quantity: 1,
                        customer: 'Juan Alejandro',
                        status: 'RETURNED',
                        typePaiement: 'Espèce',
                    },
                    {
                        id: '1000-3',
                        factureCode: 'f230fh0g3',
                        date: '2020-09-13',
                        amount: 195,
                        quantity: 3,
                        customer: 'Claire Morrow',
                        status: 'CANCELLED',
                        typePaiement: 'Espèce',
                    }
                ]
            },
            {
                id: '1001',
                code: 'nvklal433',
                name: 'Ibrahim Diallo',
                description: 'Facture Description',
                image: 'black-watch.jpg',
                price: 72,
                category: 'Accessories',
                quantity: 61,
                factureStatus: 'Payé',
                rating: 4,
                phone: '+33 02 34 56 78',
                orders: [
                    {
                        id: '1001-0',
                        factureCode: 'nvklal433',
                        date: '2020-05-14',
                        amount: 72,
                        quantity: 1,
                        customer: 'Maisha Jefferson',
                        status: 'DELIVERED',
                        typePaiement: 'Espèce',
                    },
                    {
                        id: '1001-1',
                        factureCode: 'nvklal433',
                        date: '2020-02-28',
                        amount: 144,
                        quantity: 2,
                        customer: 'Octavia Murillo',
                        status: 'PENDING',
                        typePaiement: 'Espèce',
                    }
                ]
            },
            {
                id: '1002',
                code: 'zz21cz3c1',
                name: 'Moise Kamano',
                description: 'Facture Description',
                image: 'blue-band.jpg',
                price: 79,
                category: 'Fitness',
                quantity: 2,
                factureStatus: 'Brouillon',
                rating: 3,
                phone: '+33 02 34 56 78',
                orders: [
                    {
                        id: '1002-0',
                        factureCode: 'zz21cz3c1',
                        date: '2020-07-05',
                        amount: 79,
                        quantity: 1,
                        customer: 'Stacey Leja',
                        status: 'DELIVERED',
                        typePaiement: 'Espèce',
                    },
                    {
                        id: '1002-1',
                        factureCode: 'zz21cz3c1',
                        date: '2020-02-06',
                        amount: 79,
                        quantity: 1,
                        customer: 'Ashley Wickens',
                        status: 'DELIVERED',
                        typePaiement: 'Espèce',
                    }
                ]
            },
            {
                id: '1003',
                code: '244wgerg2',
                name: 'Ali Camara',
                description: 'Facture Description',
                image: 'blue-t-shirt.jpg',
                price: 29,
                category: 'Clothing',
                quantity: 25,
                factureStatus: 'Payé',
                phone: '+33 02 34 56 78',
                rating: 5,
                orders: []
            },
            {
                id: '1004',
                code: 'h456wer53',
                name: 'Adourahmane Baldé',
                description: 'Facture Description',
                image: 'adourahmane baldé.jpg',
                price: 15,
                category: 'Accessories',
                quantity: 73,
                factureStatus: 'Payé',
                phone: '+33 02 34 56 78',
                rating: 4,
                orders: [
                    {
                        id: '1004-0',
                        factureCode: 'h456wer53',
                        date: '2020-09-05',
                        amount: 60,
                        quantity: 4,
                        customer: 'Mayumi Misaki',
                        status: 'PENDING',
                        typePaiement: 'Espèce',
                    },
                    {
                        id: '1004-1',
                        factureCode: 'h456wer53',
                        date: '2019-04-16',
                        amount: 2,
                        quantity: 30,
                        customer: 'Francesco Salvatore',
                        status: 'DELIVERED',
                        typePaiement: 'Espèce',
                    }
                ]
            },
            {
                id: '1005',
                code: 'av2231fwg',
                name: 'Oumou Sow',
                description: 'Facture Description',
                image: 'brown-purse.jpg',
                price: 120,
                category: 'Accessories',
                quantity: 0,
                factureStatus: 'Partiel',
                rating: 4,
                phone: '+33 02 34 56 78',
                orders: [
                    {
                        id: '1005-0',
                        factureCode: 'av2231fwg',
                        date: '2020-01-25',
                        amount: 120,
                        quantity: 1,
                        customer: 'Isabel Sinclair',
                        status: 'RETURNED',
                        typePaiement: 'Espèce',
                    },
                    {
                        id: '1005-1',
                        factureCode: 'av2231fwg',
                        date: '2019-03-12',
                        amount: 240,
                        quantity: 2,
                        customer: 'Lionel Clifford',
                        status: 'DELIVERED',
                        typePaiement: 'Espèce',
                    },
                    {
                        id: '1005-2',
                        factureCode: 'av2231fwg',
                        date: '2019-05-05',
                        amount: 120,
                        quantity: 1,
                        customer: 'Cody Chavez',
                        status: 'DELIVERED',
                        typePaiement: 'Espèce',
                    }
                ]
            },
            {
                id: '1006',
                code: 'bib36pfvm',
                name: 'Adourahmane Baldé',
                description: 'Facture Description',
                image: 'chakra-adourahmane baldé.jpg',
                price: 32,
                category: 'Accessories',
                quantity: 5,
                factureStatus: 'Brouillon',
                rating: 3,
                phone: '+33 02 34 56 78',
                orders: [
                    {
                        id: '1006-0',
                        factureCode: 'bib36pfvm',
                        date: '2020-02-24',
                        amount: 32,
                        quantity: 1,
                        customer: 'Arvin Darci',
                        status: 'DELIVERED',
                        typePaiement: 'Espèce',
                    },
                    {
                        id: '1006-1',
                        factureCode: 'bib36pfvm',
                        date: '2020-01-14',
                        amount: 64,
                        quantity: 2,
                        customer: 'Izzy Jones',
                        status: 'PENDING',
                        typePaiement: 'Espèce',
                    }
                ]
            },
            {
                id: '1007',
                code: 'mbvjkgip5',
                name: 'Néné Asma',
                description: 'Facture Description',
                image: 'galaxy-earrings.jpg',
                price: 34,
                category: 'Accessories',
                quantity: 23,
                factureStatus: 'Payé',
                rating: 5,
                phone: '+33 02 34 56 78',
                orders: [
                    {
                        id: '1007-0',
                        factureCode: 'mbvjkgip5',
                        date: '2020-06-19',
                        amount: 34,
                        quantity: 1,
                        customer: 'Jennifer Smith',
                        status: 'DELIVERED',
                        typePaiement: 'Espèce',
                    }
                ]
            },
            {
                id: '1008',
                code: 'vbb124btr',
                name: 'Almamy BARRY',
                description: 'Facture Description',
                image: 'game-controller.jpg',
                price: 99,
                category: 'Electronics',
                quantity: 2,
                factureStatus: 'Brouillon',
                rating: 4,
                phone: '+33 02 34 56 78',
                orders: [
                    {
                        id: '1008-0',
                        factureCode: 'vbb124btr',
                        date: '2020-01-05',
                        amount: 99,
                        quantity: 1,
                        customer: 'Jeanfrancois David',
                        status: 'DELIVERED',
                        typePaiement: 'Espèce',
                    },
                    
                ]
            },
            {
                id: '1009',
                code: 'cm230f032',
                name: 'Maladho BALDE',
                description: 'Facture Description',
                image: 'gaming-set.jpg',
                price: 299,
                category: 'Electronics',
                quantity: 63,
                factureStatus: 'Payé',
                rating: 3,
                phone: '+33 02 34 56 78',
                orders: [
                    {
                        id: '1009-0',
                        factureCode: 'cm230f032',
                        date: '2020-06-24',
                        amount: 299,
                        quantity: 1,
                        customer: 'Kadeem Mujtaba',
                        status: 'PENDING'
                    },
                    {
                        id: '1009-1',
                        factureCode: 'cm230f032',
                        date: '2020-05-11',
                        amount: 299,
                        quantity: 1,
                        customer: 'Ashley Wickens',
                        status: 'DELIVERED'
                    },
                   
                ]
            },
            {
                id: '1010',
                code: 'plb34234v',
                name: 'Gold Phone Case',
                description: 'Facture Description',
                image: 'gold-phone-case.jpg',
                price: 24,
                category: 'Accessories',
                quantity: 0,
                factureStatus: 'Partiel',
                rating: 4,
                orders: [
                    {
                        id: '1010-0',
                        factureCode: 'plb34234v',
                        date: '2020-02-04',
                        amount: 24,
                        quantity: 1,
                        customer: 'James Butt',
                        status: 'DELIVERED',
                        typePaiement: 'Espèce',
                    },
                ]
            },
            {
                id: '1011',
                code: '4920nnc2d',
                name: 'Green Earbuds',
                description: 'Facture Description',
                image: 'green-earbuds.jpg',
                price: 89,
                category: 'Electronics',
                quantity: 23,
                factureStatus: 'Payé',
                rating: 4,
                orders: [
                    {
                        id: '1011-0',
                        factureCode: '4920nnc2d',
                        date: '2020-06-01',
                        amount: 89,
                        quantity: 1,
                        customer: 'Art Venere',
                        status: 'DELIVERED',
                        typePaiement: 'Espèce',
                    }
                ]
            },
            {
                id: '1012',
                code: '250vm23cc',
                name: 'Green T-Shirt',
                description: 'Facture Description',
                image: 'green-t-shirt.jpg',
                price: 49,
                category: 'Clothing',
                quantity: 74,
                factureStatus: 'Payé',
                rating: 5,
                orders: [
                    {
                        id: '1012-0',
                        factureCode: '250vm23cc',
                        date: '2020-02-05',
                        amount: 49,
                        quantity: 1,
                        customer: 'Lenna Paprocki',
                        status: 'DELIVERED'
                    },
                    {
                        id: '1012-1',
                        factureCode: '250vm23cc',
                        date: '2020-02-15',
                        amount: 49,
                        quantity: 1,
                        customer: 'Donette Foller',
                        status: 'PENDING',
                        typePaiement: 'Espèce',
                    }
                ]
            }, 
            {
                id: '1029',
                code: 'gwuby345v',
                name: 'Yoga Set',
                description: 'Facture Description',
                image: 'yoga-set.jpg',
                price: 20,
                category: 'Fitness',
                quantity: 25,
                factureStatus: 'Payé',
                rating: 8,
                orders: [
                    {
                        id: '1029-0',
                        factureCode: 'gwuby345v',
                        date: '2020-02-14',
                        amount: 4,
                        quantity: 80,
                        customer: 'Maryann Royster',
                        status: 'DELIVERED',
                        typePaiement: 'Espèce',
                    }
                ]
            }
        ];
    },

    getFacturesMini() {
        return Promise.resolve(this.getFacturesData().slice(0, 5));
    },

    getFacturesSmall() {
        return Promise.resolve(this.getFacturesData().slice(0, 10));
    },

    getFactures() {
        return Promise.resolve(this.getFacturesData());
    },

    getFacturesWithOrdersSmall() {
        return Promise.resolve(this.getFacturesWithOrdersData().slice(0, 10));
    },

    getFacturesWithOrders() {
        return Promise.resolve(this.getFacturesWithOrdersData());
    }
};
